spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store?currentSchema=public
    username: postgres
    password: 12345

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.generate_statistics: false
      hibernate.connection.provider_disables_autocommit: false

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=200,expireAfterAccess=10s

server:
  error:
    include-message: always
    include-binding-errors: always
